'use client'

export default function PrescriptionPad({ report }: { report: string }) {
  return (
    <div className="w-full max-w-2xl p-8 bg-white shadow-2xl rounded-lg font-sans">
      <div className="flex justify-between items-start border-b-4 border-blue-600 pb-4">
        <div className="flex items-center">
          <div className="text-blue-600 font-bold text-5xl mr-4">Rx</div>
          <div>
            <h1 className="text-3xl font-bold text-gray-800">Dr. AI</h1>
            <p className="text-gray-600">MBBS, FCPS (Medicine)</p>
            <p className="text-gray-600">Dhaka Medical College & Hospital</p>
          </div>
        </div>
        <div className="text-right text-sm text-gray-600">
          <p>Date: {new Date().toLocaleDateString('en-GB')}</p>
          <p>Patient ID: 12345</p>
        </div>
      </div>
      <div className="mt-8">
        <h2 className="text-xl font-bold text-gray-700 mb-2">Patient Symptoms & Diagnosis</h2>
        <div className="p-4 bg-gray-50 rounded-lg">
          <p className="text-gray-800 whitespace-pre-wrap">{report || "No report generated."}</p>
        </div>
      </div>
      <div className="mt-8">
        <h2 className="text-xl font-bold text-gray-700 mb-2">Medication</h2>
        <div className="space-y-4">
          <div className="flex items-center">
            <p className="w-1/2 font-semibold text-gray-800">1. Placeholder Medicine A</p>
            <p className="w-1/2 text-gray-600">1 + 0 + 1 (After Meal)</p>
          </div>
          <div className="flex items-center">
            <p className="w-1/2 font-semibold text-gray-800">2. Placeholder Medicine B</p>
            <p className="w-1/2 text-gray-600">0 + 1 + 0 (Before Meal)</p>
          </div>
          <div className="flex items-center">
            <p className="w-1/2 font-semibold text-gray-800">3. Placeholder Medicine C</p>
            <p className="w-1/2 text-gray-600">1 + 1 + 1 (After Meal)</p>
          </div>
        </div>
      </div>
      <div className="mt-12 border-t-2 border-dashed pt-6 text-center text-sm text-gray-600">
        <p>This is a preliminary report generated by an AI. Please consult with a qualified doctor for a final diagnosis.</p>
        <p className="font-bold mt-2">Contact: +880 1234 567890</p>
      </div>
    </div>
  )
}